# Generated by Django 2.1.4 on 2018-12-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000000)),
                ('rules', models.CharField(max_length=1000000)),
                ('owner', models.CharField(max_length=30)),
                ('defaultAction', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.User'),
        ),
    ]
