# Generated by Django 2.1.4 on 2018-12-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20181227_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='gname',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='uname',
            new_name='user',
        ),
    ]
