# Generated by Django 2.1.4 on 2018-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20181228_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagex',
            field=models.ImageField(upload_to='labeled_images'),
        ),
    ]
