# Generated by Django 2.1.4 on 2018-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20181228_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagex',
            field=models.ImageField(upload_to='../media/labeled_images'),
        ),
    ]
