# Generated by Django 2.1.4 on 2018-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20181228_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagex',
            field=models.ImageField(default='', upload_to='labeled_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='imagex',
            field=models.ImageField(upload_to='labeled_images/'),
        ),
    ]
