# Generated by Django 2.1.4 on 2018-12-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
