# Generated by Django 2.1.4 on 2018-12-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20181226_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
