# Generated by Django 2.1.4 on 2018-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20181227_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagex',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
