# Generated by Django 2.1.4 on 2018-12-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_image_imagex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagex',
        ),
        migrations.AddField(
            model_name='user',
            name='imagex',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
