# Generated by Django 2.1.4 on 2018-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20181228_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='defaultAction',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagex',
            field=models.ImageField(blank=True, upload_to='labeled_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='rules',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
