# Generated by Django 2.1.4 on 2018-12-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20181228_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagex',
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
