# Generated by Django 2.1.4 on 2018-12-28 18:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20181228_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
