# Generated by Django 2.1.4 on 2018-12-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20181228_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='defaultAction',
            field=models.CharField(blank=True, default='ALLOW', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='rules',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
